###
//register as visitor
post http://localhost:3000/register/visitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4Yjc1YmU4MjdiYWYyMmNjNGFlMGQ4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2ODYxMjQ5fQ.FXjInQF1xoG-EZAkL7HxPMjuxkYEBOyY0lb3Fc6ckxQ
Content-Type: application/json

{
    "name":"Ng Wei Jie",
    "gender":"Male",
    "age":"22",
    "date_of_birth":"22 April 2001",
    "ethnicity":"chinese",
    "citizenship":"malaysia",
    "license_number":"111"
}


//the following are the insert of visitor doc
###
//doc expiry date means need to update doc before the date comes
post http://localhost:3000/register/visitor/doc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4Yjc1YmU4MjdiYWYyMmNjNGFlMGQ4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2ODYxMjQ5fQ.FXjInQF1xoG-EZAkL7HxPMjuxkYEBOyY0lb3Fc6ckxQ
Content-Type: application/json

{
    "doc_expiry_date":"25 March 2027",
    "job_id":"111111",
    "Mykad":"011111-10-1111"
}

###

post http://localhost:3000/register/visitor/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "address":"1,jalan 1,taman 1, 11111 klang,selangor",
    "town":"taman 1",
    "postcode":"11111",
    "state":"selangor",
    "country":"malaysia"
}

###
post http://localhost:3000/register/visitor/other
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "visitor_category":"admin as visitor",
    "telephone_number":"111111111",
    "vehicle_type":"honda",
    "vehicle_number":"bnr1111",
    "pre_register_pass_no":"1111"
}

###
post http://localhost:3000/register/visitor/additional
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "fever":"no",
    "Sore_throat":"no",
    "dry_cough":"no",
    "runny_nose":"no",
    "shortness_of_breath":"no",
    "body_ache":"no",
    "travelled_overseas_last14days":"no",
    "contact_with_person_with_covid":"no",
    "recovered_from_covid":"no",
    "covid_test":"no"
}



###
post http://localhost:3000/register/visitor/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "no_of_visitor":"1",
    "purpose_of_visit":"rent collecting",
    "To_meet_host":"Han",
    "host_info":"nothing",
    "location_department":"A-1",
    "unit_no":"1",
    "location_info":" ",
    "permit_no":"001",
    "remarks":"rent"
}

###

post http://localhost:3000/register/visitor/visitation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2ZlZmJmYWIwODE1ZjM3ZmExMzc4Iiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNjg2NjM0MzcxfQ.CGxtVAHsjucWvqq8xavaM078evm7ZKJUH0nFEZ06VrA
Content-Type: application/json

{
    "visit_date":"13 June 2023",
    "checkin_time":"10:00",
    "visit_expiry_time":"no limit",
    "checkout_time":"12:00",
    "overtime_status":"not overtime",
    "detail_id":"6487fa4c928a56a3b437c73f"

}


//admin and security read data from database based on criteria they insert
//if admin or security wants to read all doc from a collection,just put an empty json file
###
post http://localhost:3000/security/user/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{

}


###
post http://localhost:3000/security/user/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4Yjc1YmU4MjdiYWYyMmNjNGFlMGQ4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2ODYxMjQ5fQ.FXjInQF1xoG-EZAkL7HxPMjuxkYEBOyY0lb3Fc6ckxQ

{
    "username":"NG"
}

###
post http://localhost:3000/security/visitor/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "_id":"6487f98c928a56a3b437c716"
}

###
post http://localhost:3000/security/doc/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "job_id":"111111"
}

###
post http://localhost:3000/security/address/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0

{
    "town":"taman 1"
}

###
post http://localhost:3000/security/other/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "vehicle_type":"honda"
}

###
post http://localhost:3000/security/additional/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "fever":"no"
}

###
post http://localhost:3000/security/blacklist/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4OTExZGM5MTU0Mjc5MjY0NjhhMjhmIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NzA0NjA2fQ.Ho9ZtsmJTjl5qlVt2Yi9D4pK5asoG92_4TEUn6z-wXA
Content-Type: application/json

{
    "blacklist_status":"no"
}

###
post http://localhost:3000/security/detail/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0

{
    "host_info":"nothing"
}

###
post http://localhost:3000/security/visitation/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
   
}


//update(id of specific document is required)
###
patch http://localhost:3000/security/visitor/update/6487f98c928a56a3b437c716
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2ZlZmJmYWIwODE1ZjM3ZmExMzc4Iiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNjg2NjM0MzcxfQ.CGxtVAHsjucWvqq8xavaM078evm7ZKJUH0nFEZ06VrA
Content-Type: application/json

{
    "name":"tan"
}

###
patch http://localhost:3000/security/user/update/6487f8a9928a56a3b437c6fd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2ZlZmJmYWIwODE1ZjM3ZmExMzc4Iiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNjg2NjM0MjQxfQ.bae-pG3LlUOt5P-2-nYW8DGRPoAOJkc-ZZjk1ITTRvE
Content-Type: application/json

{
    "age":"1000"
}

###
patch http://localhost:3000/security/doc/update/6487f9a3928a56a3b437c71c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "Mykad":"000000000"
}

###
patch http://localhost:3000/security/address/update/6487f9d1928a56a3b437c723
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "town":"taman 22222"
}

###
patch http://localhost:3000/security/other/update/6487fa08928a56a3b437c72a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "vehicle_number":"urr777"
}

###
patch http://localhost:3000/security/additional/update/6487fa11928a56a3b437c731
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "fever":"yes"
}


//the following can be used by both admin and security
###
patch http://localhost:3000/security/blacklist/update/648911ed915427926468a299
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4OTExZGM5MTU0Mjc5MjY0NjhhMjhmIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NzA0NjA2fQ.Ho9ZtsmJTjl5qlVt2Yi9D4pK5asoG92_4TEUn6z-wXA
Content-Type: application/json

{
    "blacklist_status":"yes",
    "reason":"overtime on visitation",
    "remark":"nothing"
}

###
patch http://localhost:3000/security/detail/update/6487fa4c928a56a3b437c73f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "To_meet_host":"Chua"
}

###
patch http://localhost:3000/security/visitation/update/6487fa8c928a56a3b437c746
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4N2Y4YWE5MjhhNTZhM2I0MzdjNzAwIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2NjMyNjUxfQ.Z6-ygCNQUM1uH6KgrEAhIFLAh8wiWVSfW8xL9wFr5F0
Content-Type: application/json

{
    "checkout_time":"23:00"
}

//admin wanst to delete a visitor
//enter visitor's id in url
###
delete http://localhost:3000/admin/visitor/deleteall/648b7633827baf22cc4ae0fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4Yjc4OWZlMTEyZTZlMDg0YjQ2MmVmIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2ODYyNTI1fQ.mqfuQ7IJqgoJ6Q7NRIDNULOtscJ6ld3s9u8vdcfchew

//admin wants to delete a user account
###
delete http://localhost:3000/admin/user/delete/648b789fe112e6e084b462ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4Yjc4OWZlMTEyZTZlMDg0YjQ2MmVmIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2ODYyNTI1fQ.mqfuQ7IJqgoJ6Q7NRIDNULOtscJ6ld3s9u8vdcfchew




