
//test to see what is encoded in jwt
###
get http://localhost:3000/showjwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4NzlhY2VjYTg5OGNmYzQ2ODgwMzIxIiwicm9sZSI6InZpc2l0b3IiLCJpYXQiOjE2ODY2MDg2MDZ9.jL6Tk01lECuz49CtSxlwrg_lDpz_DQd1iQvpOs2iIx8

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username":"Tan",
    "password":"1234567",
    "name":"Tan Le",
    "gender":"Female",
    "age":"25",
    "role":"security"
}

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username":"Chan",
    "password":"123456",
    "name":"Chan Zen Yang",
    "gender":"Male",
    "age":"22",
    "role":"visitor"
}

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username":"Ali",
    "password":"123456",
    "name":"Alili",
    "gender":"Male",
    "age":"22",
    "role":"visitor"
}

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username":"NG",
    "password":"123456",
    "name":"Ng Wei Jie",
    "gender":"Male",
    "age":"22",
    "role":"admin"
}

###
Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"NG",
    "password":"123456"
}

###
Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"Chan",
    "password":"123456"
}

###
Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"Tan",
    "password":"1234567"
}

###
Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"Ali",
    "password":"123456"
}

###
patch http://localhost:3000/logout
